// ===========================================================================
// artifact-cache.mjs — Stable Artifact Cache for Resume Research (Stage -1)
//
// Defines which artifacts are "stable" (regenerated only on commit change)
// vs "volatile" (recreated each analysis round).
//
// Stable artifacts are persisted to working directory and reused across
// analysis runs unless the repository commit changes.
//
// Usage:
//   import { resumeResearch, loadStableArtifact, saveStableArtifact } from "./artifact-cache.mjs";
//   const result = await resumeResearch(workDir, repoPath);
//   if (result.resumed && result.commitUnchanged) {
//     // Skip re-scan, reuse cached artifacts
//   }
// ===========================================================================
import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join } from "node:path";
import { execSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Stable Artifact Definitions
// ---------------------------------------------------------------------------

/**
 * Stable artifacts are regenerated ONLY when commit changes.
 * Each entry specifies: name (used as key), filename (relative to workDir),
 * description (what it contains), and whether it is REQUIRED for resume.
 *
 * "禁止重新生成" unless commit changed.
 */
export const STABLE_ARTIFACTS = [
  {
    name: "repository-profile",
    filename: "repository-profile.json",
    description: "Repository type, language, file counts, entrypoints, build system",
    required: true,
  },
  {
    name: "directory-tree",
    filename: "directory-tree.json",
    description: "Full directory listing (flat file and directory paths, counts)",
    required: true,
  },
  {
    name: "symbol-index",
    filename: "symbol-index.json",
    description: "Key symbols extracted from source code (functions, classes, exports)",
    required: false,
  },
  {
    name: "git-summary",
    filename: "git-summary.json",
    description: "Git log analysis (commit frequency, contributors, major change boundaries)",
    required: false,
  },
  {
    name: "evidence-index",
    filename: "evidence-index.json",
    description: "Index of files read during mechanical analysis (path + purpose only, not content)",
    required: false,
  },
];

/**
 * Volatile artifacts — recreated each analysis run.
 * NOT cached; regenerated by their respective stages.
 */
export const VOLATILE_ARTIFACTS = [
  "context.json",
  "repository-model.json",
  "report.md",
  "questions/round-*.json",
  "questions/summary.json",
];

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

async function fileExists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get current HEAD commit hash of a git repository.
 * Returns null if repo is not a git repository.
 */
export function getCurrentCommit(repoPath) {
  try {
    return execSync("git rev-parse HEAD", {
      cwd: repoPath,
      encoding: "utf-8",
      timeout: 5000,
    }).trim();
  } catch {
    return null;
  }
}

/**
 * Get diff between two commits (list of changed files).
 */
export function getChangedFiles(repoPath, fromCommit, toCommit = "HEAD") {
  try {
    const diff = execSync(`git diff --name-only ${fromCommit}..${toCommit}`, {
      cwd: repoPath,
      encoding: "utf-8",
      timeout: 10000,
    }).trim();
    return diff ? diff.split("\n") : [];
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Artifact Cache Operations
// ---------------------------------------------------------------------------

/**
 * Load a stable artifact from the working directory.
 * @param {string} workDir
 * @param {string} name - artifact name (from STABLE_ARTIFACTS)
 * @returns {Promise<object|null>} parsed artifact data, or null if not found
 */
export async function loadStableArtifact(workDir, name) {
  const def = STABLE_ARTIFACTS.find((a) => a.name === name);
  if (!def) throw new Error(`Unknown stable artifact: ${name}`);
  const path = join(workDir, "artifacts", def.filename);
  if (!(await fileExists(path))) return null;
  try {
    const content = await readFile(path, "utf-8");
    return JSON.parse(content);
  } catch {
    return null;
  }
}

/**
 * Save a stable artifact to the working directory.
 * @param {string} workDir
 * @param {string} name - artifact name (from STABLE_ARTIFACTS)
 * @param {object} data
 */
export async function saveStableArtifact(workDir, name, data) {
  const def = STABLE_ARTIFACTS.find((a) => a.name === name);
  if (!def) throw new Error(`Unknown stable artifact: ${name}`);
  const dir = join(workDir, "artifacts");
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, def.filename), JSON.stringify(data, null, 2), "utf-8");
}

/**
 * Check if all REQUIRED stable artifacts exist.
 * @param {string} workDir
 * @returns {Promise<boolean>}
 */
export async function allStableArtifactsExist(workDir) {
  const required = STABLE_ARTIFACTS.filter((a) => a.required);
  for (const def of required) {
    const path = join(workDir, "artifacts", def.filename);
    if (!(await fileExists(path))) return false;
  }
  return true;
}

/**
 * List which stable artifacts are missing (for partial resume).
 * @param {string} workDir
 * @returns {Promise<string[]>} names of missing artifacts
 */
export async function missingStableArtifacts(workDir) {
  const missing = [];
  for (const def of STABLE_ARTIFACTS) {
    const path = join(workDir, "artifacts", def.filename);
    if (!(await fileExists(path))) {
      missing.push(def.name);
    }
  }
  return missing;
}

// ---------------------------------------------------------------------------
// Meta.json Operations
// ---------------------------------------------------------------------------

/**
 * Load meta.json from working directory.
 * Returns null if not found or invalid.
 */
export async function loadMeta(workDir) {
  const path = join(workDir, "meta.json");
  if (!(await fileExists(path))) return null;
  try {
    const content = await readFile(path, "utf-8");
    return JSON.parse(content);
  } catch {
    return null;
  }
}

/**
 * Write or update meta.json.
 */
export async function writeMeta(workDir, meta) {
  await writeFile(
    join(workDir, "meta.json"),
    JSON.stringify(meta, null, 2),
    "utf-8"
  );
}

// ---------------------------------------------------------------------------
// Stage -1: Resume Research
// ---------------------------------------------------------------------------

/**
 * Resume Research (Stage -1).
 *
 * Determines whether a previous analysis can be resumed, and what can be
 * safely reused vs needs regeneration.
 *
 * @param {string} workDir - working directory for the repository
 * @param {string} repoPath - absolute path to the repository
 * @returns {Promise<{
 *   resumed: boolean,           // whether prior analysis exists
 *   commitUnchanged: boolean,   // whether commit matches last_analyzed_commit
 *   commit: string|null,        // current HEAD commit (null if not git)
 *   meta: object|null,          // loaded meta.json
 *   artifactsReady: boolean,    // whether all required stable artifacts exist
 *   missingArtifacts: string[], // names of missing stable artifacts
 *   changedFiles: string[],     // files changed since last_analyzed_commit
 * }>}
 */
export async function resumeResearch(workDir, repoPath) {
  // Check if working directory exists
  if (!(await fileExists(workDir))) {
    return {
      resumed: false,
      commitUnchanged: false,
      commit: getCurrentCommit(repoPath),
      meta: null,
      artifactsReady: false,
      missingArtifacts: STABLE_ARTIFACTS.filter((a) => a.required).map((a) => a.name),
      changedFiles: [],
    };
  }

  // Load meta.json
  const meta = await loadMeta(workDir);
  if (!meta) {
    // Working directory exists but meta is missing — partial state
    return {
      resumed: true,
      commitUnchanged: false,
      commit: getCurrentCommit(repoPath),
      meta: null,
      artifactsReady: false,
      missingArtifacts: STABLE_ARTIFACTS.filter((a) => a.required).map((a) => a.name),
      changedFiles: [],
    };
  }

  const commit = getCurrentCommit(repoPath);
  const lastCommit = meta.last_analyzed_commit || "unknown";
  const commitUnchanged = commit === lastCommit && commit !== null;

  // Check artifacts
  const artifactsReady = await allStableArtifactsExist(workDir);
  const missing = artifactsReady ? [] : await missingStableArtifacts(workDir);

  // Get changed files if commit changed
  let changedFiles = [];
  if (!commitUnchanged && commit && lastCommit && lastCommit !== "unknown") {
    changedFiles = getChangedFiles(repoPath, lastCommit, commit);
  }

  return {
    resumed: true,
    commitUnchanged,
    commit,
    meta,
    artifactsReady,
    missingArtifacts: missing,
    changedFiles,
  };
}
